name: Go
on: pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
    - uses: actions/checkout@v2

    - name: Run go vet
      run: go vet ./...

    - name: Run staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest && ~/go/bin/staticcheck ./...

    - name: Build
      run: go install ./...
